# -*- coding: utf-8 -*-
# Auto-generated by install_mcp.py
import asyncio
import os
import sys

# 将本目录及子模块路径加入环境变量
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
sys.path.append(os.path.join(current_dir, "miot_kit"))

# Windows 平台动态链接库不存在的 Monkey Patch
import platform
if platform.system().lower() == "windows":
    class FakeLib:
        def __getattr__(self, name):
            if name == "miot_camera_version":
                return lambda *args, **kwargs: b"0.0.0-fake"
            return lambda *args, **kwargs: 0
            
    import miot.camera
    miot.camera._load_dynamic_lib = lambda: FakeLib()

from miot.client import MIoTClient
from miot.spec import MIoTSpecParser
from miot.i18n import MIoTI18n
from miot.mcp import MIoTDeviceMcp, MIoTDeviceMcpInterface
from miot.storage import MIoTStorage

client = None
device_mcp = None

async def main():
    global client, device_mcp
    cache_path = os.path.join(os.path.expanduser("~"), ".miot_cache")
    
    # 初始化 Storage 并加载本地凭证
    storage = MIoTStorage(cache_path)
    uuid = await storage.load_async(domain="cloud", name="uuid", type_=str)
    oauth_data = await storage.load_async(domain="cloud", name="oauth_info", type_=dict)
    
    if not oauth_data:
        raise RuntimeError("未在缓存中发现登录凭证，请先完成米家 OAuth 授权登录！")
        
    client = MIoTClient(
        uuid=uuid,
        redirect_uri="http://127.0.0.1",
        cache_path=cache_path,
        oauth_info=oauth_data,
        cloud_server="cn"
    )
    await client.init_async()
    
    i18n = MIoTI18n(lang="zh-Hans")
    await i18n.init_async()
    
    spec_parser = MIoTSpecParser(storage=client.storage, lang="zh-Hans")
    await spec_parser.init_async()
    
    device_mcp = MIoTDeviceMcp(
        interface=MIoTDeviceMcpInterface(
            translate_async=i18n.translate_async,
            get_devices_async=client.get_devices_async,
            get_homes_async=client.get_homes_async,
            get_prop_async=client.http_client.get_prop_async,
            set_prop_async=client.http_client.set_prop_async,
            action_async=client.http_client.action_async
        ),
        spec_parser=spec_parser
    )
    await device_mcp.init_async()
    
    try:
        # 直接利用内建的 mcp_instance 异步启动 stdio 服务器，关闭 banner 避免污染 stdout
        await device_mcp.mcp_instance.run_stdio_async(show_banner=False)
    finally:
        if client:
            await client.deinit_async()

if __name__ == "__main__":
    asyncio.run(main())
